#!/bin/bash

make > /dev/null

valgrind ./target/crossw data/Crossword$1.txt -dict data/Words.txt
#callgrind_annotate > profiler.out
#rm -rf callgrind.out.*

# --dsymutil=yes --tool=callgrind
make clean > /dev/null
